const adjectives = {
	'beautiful': 'красивый',
	'ugly': 'уродливый',
	'affirmative': 'утвердительный',
	'negative': 'отрицательный',
	'bad': 'плохой',
	'good': 'хороший',
	'dull': 'понурый, скучный',
	'voluntary': 'добровольный',
	'compulsory': 'принудительный',
	'awake': 'бодрствующий',
	'asleep': 'спящий',
	'complicated': 'сложный',
	'simple': 'простой',
	'fearless': 'бесстрашный',
	'afraid': 'испуганный',
	'careless': 'неосторожнй, беспечный',
	'careful': 'осторожный',
	'natural': 'естественный',
	'artificial': 'искуственный',
	'interesting': 'интересный',
	'boring': 'скучный',
	'moderate': 'умеренный',
	'extreme': 'крайний, экстремальный, несусветный',
	'modern': 'современный',
	'ancient': 'древний',
	'dead': 'мертвый',
	'alive': 'живой',
	'different': 'различный, не такой',
	'odd': 'нечетный',
	'even': 'четный',
	'blunt': 'тупой',
	'sharp': 'острый',
	'sweet': 'сладкий',
	'bitter': 'горький',
	'advanced': 'передовой, продвинутый',
	'elementary': 'елементарный, начальный',
	'full': 'полный',
	'empty': 'пустой',
	'small': 'маленький',
	'big': 'большой',
	'worst': 'худший',
	'best': 'лучший',
	'hardworking': 'трудолюбивый',
	'lazy': 'ленивый',
	'dormant': 'дремлющий',
	'active': 'активный',
	'accidental': 'случайный',
	'intentional': 'преднамеренный',
	'difficult': 'трудный',
	'easy': 'легкий',
	
};