const nouns = {
	'south': 'юг',
	'north': 'север',
	'west': 'запад',
	'east': 'восток',
	'foreground': 'передний план',
	'background': 'задний план',
	'dawn': 'рассвет',
	'dusk': 'сумерки',
	'child': 'ребенок',
	'adult': 'взрослый',
	'tragedy': 'трагедия',
	'comedy': 'комедия',
	'devil': 'дьявол',
	'angel': 'ангел',
	'cowardice': 'трусость',
	'bravery': 'храбрость',
	'abundance': 'избыток',
	'lack': 'недостаток',
	'enemy': 'враг',
	'friend': 'друг',
	'absence': 'отсутствие',
	'presence': 'присутствие',
	'descendant': 'потомок',
	'ancestor': 'предок',
	'bottom': 'низ, нижний',
	'top': 'вершина',
	'exit': 'выход',
	'entrance': 'вход',
	'end': 'конец',
	'beginning': 'начало',
	
};