const nouns = {
	'south': 'юг',
	'north': 'север',
	'west': 'запад',
	'east': 'восток',
	'foreground': 'передний план',
	'background': 'задний план',
	'dawn': 'рассвет',
	'dusk': 'сумерки',
	'child': 'ребенок',
	'adult': 'взрослый',
	'tragedy': 'трагедия',
	'comedy': 'комедия',
	'devil': 'дьявол',
	'angel': 'ангел',
	'cowardice': 'трусость',
	'bravery': 'храбрость',
	'abundance': 'избыток',
	'lack': 'недостаток',
	'enemy': 'враг',
	'friend': 'друг',
	'absence': 'отсутствие',
	'presence': 'присутствие',
	'descendant': 'потомок',
	'ancestor': 'предок',
	'bottom': 'низ, нижний',
	'top': 'вершина',
	'exit': 'выход',
	'entrance': 'вход',
	'end': 'конец',
	'beginning': 'начало',
	'guest': 'гость',
	'host': 'хозяин',
	'giant': 'гигант',
	'dwarf': 'карлик',
	'past': 'прошлое',
	'future': 'будущее',
	'valley': 'долина',
	'mountain': 'гора',
	'noise': 'шум',
	'cry': 'плачь',
	'laugh': 'смех',
	'defeat': 'поражение',
	'victory': 'победа',
	'village': 'деревня',
	'city': 'город',
	'peace': 'мир',
	'war': 'война',
	'sea': 'море',
	'land': 'земля, суша',
	'departure': 'отправление',
	'arrival': 'прибытие',
	'finish': 'финиш, окончание, конец',
	'start': 'старт, начало',
	'timidity': 'робость',
	'courage': 'храбрость',
	'reply': 'ответ',
	'question': 'вопрос',
	'periphery': 'периферия',
	'centre': 'центр',
	'ceiling': 'потолок',
	'floor': 'пол',
	'professional': 'профессионал',
	'amateur': 'любитель, диллетант',
	
};